name: Build with Maven and run
on: [push, workflow_dispatch]

jobs:
  build_with_maven:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v4.1.5
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Project with Maven
        run: mvn clean package
      - name: Run Application
        run:  java -jar java-trainee-edu/target/java-trainee-edu-1.0-SNAPSHOT.jar